# Generated by Django 3.2.4 on 2021-06-22 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acceptance_rate', models.FloatField()),
                ('average_percentage_class', models.FloatField()),
                ('average_percentage_ne', models.FloatField()),
                ('sat_averge', models.FloatField()),
                ('phy_subj_average', models.FloatField()),
                ('math_subj_average', models.FloatField()),
                ('bio_subj_average', models.FloatField()),
                ('chem_subj_average', models.FloatField()),
                ('toelf_average', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.IntegerField()),
                ('phy_subj', models.IntegerField()),
                ('math_subj', models.IntegerField()),
                ('bio_subj', models.IntegerField()),
                ('chem_subj', models.IntegerField()),
                ('toelf', models.IntegerField()),
                ('report_percentage', models.FloatField()),
                ('national_exams', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='scholarGuide.school')),
            ],
        ),
    ]
